# Generated by Django 4.2.1 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0004_test_result_side_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutotuneClientStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=128, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("idle", "idle"), ("running", "running"), ("error", "error")],
                        default="idle",
                        max_length=16,
                    ),
                ),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("current_test_id", models.BigIntegerField(blank=True, null=True)),
                ("origin", models.CharField(blank=True, max_length=64, null=True)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=64)),
                ("last_error_message", models.CharField(blank=True, default="", max_length=256)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
