# Generated by Django 4.2.1 on 2026-08-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0005_autotuneclientstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutotuneUploadCapability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.CharField(max_length=64, unique=True)),
                ("verifier", models.CharField(max_length=256)),
                ("enabled", models.BooleanField(default=True)),
                ("scope", models.CharField(default="network_upload", max_length=64)),
                ("engine", models.CharField(default="tanuki-", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AutotuneNetworkRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_sha256", models.CharField(max_length=64, unique=True)),
                ("byte_size", models.BigIntegerField()),
                (
                    "origin",
                    models.CharField(default="autotune_acceptance", max_length=64),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("token_id", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "network",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autotune_registration",
                        to="OpenBench.network",
                    ),
                ),
            ],
        ),
    ]
