"""
Django settings for OpenSite project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
SECRET_KEY = '@!zw2l8til1(0eb_nk+1w!(n78gqm&u)s)_v7#k6iseia@g9q0'
DEBUG = os.environ.get('SHOGIBENCH_DEBUG', '').strip().lower() in {
    '1', 'true', 'yes', 'on',
}

# Never expose credential-bearing request fields in Django exception reports,
# including when an operator explicitly enables DEBUG for local diagnosis.
DEFAULT_EXCEPTION_REPORTER_FILTER = (
    'OpenSite.exception_filter.CredentialSafeExceptionReporterFilter'
)
DEFAULT_EXCEPTION_REPORTER = (
    'OpenSite.exception_filter.CredentialSafeExceptionReporter'
)

ALLOWED_HOSTS = [
    'kishibe.dyndns.tv',
    'bench.kishibe.dyndns.tv',
    'localhost',
    '127.0.0.1',
]

HTML_MINIFY   = True
APPEND_SLASH  = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

SETTINGS_DIR  = os.path.dirname(__file__)
PROJECT_PATH  = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH  = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'Templates')

MEDIA_URL  = '/Media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Media')

INSTALLED_APPS = [
    'OpenBench',
    'OpenBench.templatetags',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'OpenSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'OpenSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

CSRF_TRUSTED_ORIGINS = [
    'https://kishibe.dyndns.tv',
    'https://bench.kishibe.dyndns.tv',
]


def read_systemd_credential(name):
    credential_directory = os.environ.get('CREDENTIALS_DIRECTORY')
    if not credential_directory:
        return None

    try:
        value = Path(credential_directory, name).read_text(encoding='utf-8').strip()
    except (OSError, UnicodeError):
        return None

    if not value or any(character.isspace() for character in value):
        return None

    return value


GMAIL_USER = os.environ.get('GMAIL_USER')
GMAIL_APP_PASSWORD = read_systemd_credential('gmail-app-password')

if GMAIL_USER and not GMAIL_APP_PASSWORD:
    raise RuntimeError('Gmail credential is unavailable')

# Separate file-backed capabilities for the managed autotune client and the
# read-only controller. Token values are never loaded into source configuration.
AUTOTUNE_CLIENT_TOKEN_FILE = os.environ.get('SHOGIBENCH_AUTOTUNE_CLIENT_TOKEN_FILE', '')
AUTOTUNE_LOOP_TOKEN_FILE = os.environ.get('SHOGIBENCH_AUTOTUNE_LOOP_TOKEN_FILE', '')

if GMAIL_USER and GMAIL_APP_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = GMAIL_USER
    EMAIL_HOST_PASSWORD = GMAIL_APP_PASSWORD
    DEFAULT_FROM_EMAIL = GMAIL_USER
